### ISSUE TITLE
ImportError: Wasmer is not available on this system

### ISSUE THREAD

**Issue by fanym919** [wasmerio/wasmer-python#539]
I am using Python 3.6.9 on Ubuntu 18.04.5, and I am getting the following error,

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fanyo/.local/lib/python3.6/site-packages/wasmer/__init__.py", line 1, in <module>
    raise ImportError("Wasmer is not available on this system")
ImportError: Wasmer is not available on this system

**Comment by Artemis21** [comment]
Same error. ARM64, Kubuntu 21.04, Python 3.10.

**Comment by HeZhYang** [comment]
same error.
``` ts@ts-OptiPlex-7080:~/project/android_CNFW/wasm$ uname -a
Linux ts-OptiPlex-7080 5.13.0-40-generic #45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
ts@ts-OptiPlex-7080:~/project/android_CNFW/wasm$ python3 hello.py 
Traceback (most recent call last):
  File "hello.py", line 1, in <module>
    from wasmer import engine, Store, Module, Instance
  File "/home/ts/.local/lib/python3.8/site-packages/wasmer/__init__.py", line 1, in <module>
    raise ImportError("Wasmer is not available on this system")
ImportError: Wasmer is not available on this system
```

**Comment by dastanbeksamatov** [comment]
was able to fix the issue by using Python version 3.9.

**Comment by kenorb** [comment]
Same error using GitHub Actions using `ubuntu-latest` image.

```
Current runner version: '2.295.0'
Operating System  Ubuntu 20.04.4 LTS
Environment: ubuntu-20.04
Version: 20220814.1
```

while installing `wasmer` package via `pip3`.

```
File "/home/runner/.local/lib/python3.8/site-packages/wasmer/__init__.py", line 1, in <module>
  raise ImportError("Wasmer is not available on this system")
```

**Comment by luisobregon21** [comment]
Been having this same issue... any updates??
