### ISSUE TITLE
Calling function with complex data structures as input?

### ISSUE THREAD

**Issue by mishushakov** [wasmerio/wasmer-python#654]
Let's say I have following function (in rust), compiled to `wasm32-wasi` target:

```rs
pub fn add_a(input: Vec<i32>) -> i32 {
  return input.into_iter().reduce(|a, b| a + b).unwrap()
}
```

I want to execute it with wasmer for Python

Here is what I tried:

```py
print(instance.exports.add_a([5, 4]))
```

Error I'm getting:

```
Traceback (most recent call last):
  File "/Users/mish/Downloads/wasm-python/src/test.py", line 29, in <module>
    print(instance.exports.add_a([5, 4]))
TypeError: 'list' object cannot be converted to 'PyLong'
```

If I try:

```py
print(instance.exports.add_a(5, 4))
```

I'm getting:

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:29:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/Users/mish/Downloads/wasm-python/src/test.py", line 29, in <module>
    print(instance.exports.add_a(5, 4))
RuntimeError: RuntimeError: unreachable
```

How do I pass complex data structures to wasm-exported functions?

**Comment by mishushakov** [comment]
Ok, I understood now. WebAssembly doesn't understand anything but numbers. This is why you never see examples of using WebAssembly with strings
