### ISSUE TITLE
wasmer not available/working on python 3.10, is on 3.9

### ISSUE THREAD

**Issue by jmgurney** [wasmerio/wasmer-python#680]
Thanks for the bug report!

### Describe the bug

Attempting to run wasmer on Python 3.10 on an arm Mac fails w/:
```
ImportError: Wasmer is not available on this system                                                                                            
```

But does work fine w/ Python 3.9.

### Steps to reproduce

1. Using python3.10, make virtualenv: `python -m venv p; . ./p/bin/activate`
2. Install wasmer: `pip install wasmer`
3. Try to import wasmer: `python -c 'import wasmer'` 

### Expected behavior

Per the `README.md`, it says that 3.10 is supported.

### Actual behavior

Error message per above generated:
```
$ python -c 'import wasmer; from wasmer_compiler_llvm import Compiler'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jmg/wasm/wasibox/p3.10/lib/python3.10/site-packages/wasmer/__init__.py", line 1, in <module>
    raise ImportError("Wasmer is not available on this system")
ImportError: Wasmer is not available on this system
```

### Additional context

This is an Apple M1 cpu, which though not listed as supported, as is demonstrated above, appears to work fine on 3.9, or at least does not raise an error.

**Comment by alex-first-resonance** [comment]
Ive struggled with this issue as well, except I'm simply trying to use the headless version. I fixed it on my M1 by removing the extra cargo args in the justfile. 

This seems to be a recurring failure where the package just never quite gets there, and all that arrives is the setup.py and an empty `/__init__.py` which only has the line to raise this error. 

Since the last update to the repo was over a year ago, with so many active errors, is this package abandoned or indirectly deprecated?

**Comment by alex-first-resonance** [comment]
I'm in the process of working through this as well.

What I've found works is to directly reference the compiled wheel for the python version in `requirements.txt` or equivalent, as so:
> https://github.com/wasmerio/wasmer-python/releases/download/1.1.0/wasmer-1.1.0-cp310-cp310-manylinux_2_24_x86_64.whl

By just referencing the compiled wheel, you'll get the expected binary.

The source of the problem seems to be a lack of linking (arch mismatch maybe?) somewhere, but in the meantime I noticed I wasn't getting the wheel binary (essentially a default failback) and so explicitly referencing it helped.

**Comment by Zambonilli** [comment]
@alex-first-resonance You mentioned that you were able to get wasm working on an osX m processor by directly referencing the url to a release whl file. I'm not seeing an arm whl file in the releases and pip is not working well with rosetta to emulate any of the x86_64 or amd64 release whl files. I'm on a m3 chip but want to confirm you were able to get one of the x86_64 or amd64 whl to work with an m1 chip.
